# Generated by Django 4.1 on 2022-09-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTenis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrantesClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='CatCuarta',
        ),
        migrations.DeleteModel(
            name='CatDamas',
        ),
        migrations.DeleteModel(
            name='CatTercera',
        ),
        migrations.DeleteModel(
            name='SociosTenis',
        ),
    ]
