# Generated by Django 4.1 on 2022-09-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTenis', '0004_proveedorindumentaria_restobarclub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProveedorIndumentaria',
        ),
    ]
