# Generated by Django 4.1 on 2022-09-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTenis', '0005_delete_proveedorindumentaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorIndumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ropa', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
            ],
        ),
    ]
