# Generated by Django 4.1 on 2022-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTenis', '0006_proveedorindumentaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('partidos', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Restobarclub',
        ),
    ]
